default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  reaping_frequency: 10
  host: localhost

development:
  <<: *default
  database: twilreapi_development

test:
  <<: *default
  database: twilreapi_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
